# .github/workflows/ci.yml
name: CI with CVMFS

on: [push, pull_request]

jobs:
  build:
    # use alma9 for compatibility with CVMFS
    runs-on: ubuntu-latest
    container:
      image: registry.cern.ch/ghcr.io/acts-project/ubuntu2404:85
      credentials:
        username: ${{ secrets.CERN_REGISTRY_USERNAME }}
        password: ${{ secrets.CERN_REGISTRY_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v5.5
        with:
          cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'

      - name: Use software from CVMFS
        run: |
          source /cvmfs/sft.cern.ch/lcg/views/LCG_107/x86_64-ubuntu2404-gcc13-opt/setup.sh
          python --version
          chmod +x build_all.sh
          ./build_all.sh

      



