# .github/workflows/ci.yml
name: CI with CVMFS

on: [push, pull_request]

jobs:
  build:
    # use alma9 for compatibility with CVMFS
    runs-on: ubuntu-latest
    container:
      image: almalinux:9

    steps:
      - uses: actions/checkout@v4

      - name: Setup CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4
        with:
          cvmfs_repositories: 'sft.cern.ch,geant4.cern.ch'

      - name: Use software from CVMFS
        run: |
          source /cvmfs/sft.cern.ch/lcg/views/LCG_107/x86_64-el9-gcc13-opt/setup.sh
          python --version
          chmod +x build_all.sh
          ./build_all.sh

      



